### ISSUE TITLE
Enum value alised to PascalCase by default

### ISSUE THREAD

**Issue by callumforrester** [wyfo/apischema#162]
https://github.com/wyfo/apischema/pull/142 means that all Python enum values are converted to `PascalCase` during schema creation. 

Presumably this comes from the Apollo docs specification: https://www.apollographql.com/docs/apollo-server/schema/schema/ 
However there seems to be some dispute around this, the GraphQL spec recommends (but does not mandate) enums should be `ALL_CAPS_SNAKE_CASE`: https://spec.graphql.org/draft/#sec-Enum-Value.

I'm wondering if an injectable aliaser, similar to the one for queries, should be considered to resolve all possible use cases.

@wyfo Would be interested to hear your thoughts. Am I just looking at the wrong spec?

**Comment by wyfo** [comment]
> #142 means that all Python enum values are converted to PascalCase during schema creation.

And that's a big mistake of mine. It should have been `ALL_CAPS` if enforced, or better not enforced and configurable. 

I'm sorry for the inconvenience, and I will release a patch tonight which remove this wrong case enforcement, which should never have been added here.

> Presumably this comes from the Apollo docs specification: https://www.apollographql.com/docs/apollo-server/schema/schema/
However there seems to be some dispute around this, the GraphQL spec recommends (but does not mandate) enums should be ALL_CAPS_SNAKE_CASE: https://spec.graphql.org/draft/#sec-Enum-Value.

[Apollo documentation](https://www.apollographql.com/docs/apollo-server/schema/schema/#naming-conventions) follows the convention of *GraphQL* specifications. It's written `ALL_CAPS` for values, and `PascalCase` for type name. So I was completely wrong when I've introduced this change.

Anyway, my main issue with enumerations is the difference between JSON and *GraphQL* approach. *apischema* was a JSON (de)serialization library before also becoming *GraphQL* one.  That's why `Enum` values are used. But concerning GraphQL, which has only string enumeration, using names would have been a more logical choice. I wanted to keep a coherency between both, so I've kept the first approach.

However, I'm still not satisfied with the handling of `Enum` for *GraphQL*. #160 makes things a little better, but that's not enough. I think I should change the default behavior of *apischema* for *GraphQL* enumerations and use names, and add a `enum_aliaser` parameter to `graphql_schema` with an `ALL_CAPS ` aliaser as default value. That would be a breaking change, but because it currently accept only string `Enum`, which usually doesn't have values different of their names, the change will not be so breaking.

> I'm wondering if an injectable aliaser, similar to the one for queries, should be considered to resolve all possible use cases.

As written above, I agree with this idea. Have you also an opinion about using `Enum` names instead of values will also be better thing for *GraphQL*?

**Comment by callumforrester** [comment]
Thanks for coming back.

At the moment apischema enforces string enums, so I imagine most people will have made names reflect values because they need a string and just write the one that's already there, e.g.
```python
class MyEnum(Enum):
    A = "A"
    B = "B"
    C = "C"
```
So although its a breaking change to use the enum names I don't think it will break _that_ many things. I think it's a good idea.

**Comment by wyfo** [comment]
Closed by #165
