### ISSUE TITLE
GQL: Cannot have multiple queries returning a union

### ISSUE THREAD

**Issue by callumforrester** [wyfo/apischema#175]
```python
from dataclasses import dataclass
from typing import Union

from apischema.graphql import graphql_schema
from graphql.utilities import print_schema


@dataclass
class Foo:
    a: int


@dataclass
class Bar:
    b: str


def test_multiple_queries_returning_union():
    def first() -> Union[Foo, Bar]:
        ...
    
    def second() -> Union[Foo, Bar]:
        ...

    schema = graphql_schema(query=[first, second])

```

The code above yields the following:

```
TypeError: Schema must contain uniquely named types but contains multiple types named 'FooOrBar'.
venv/lib/python3.9/site-packages/graphql/type/schema.py:242: TypeError
```

I've had a look through the code to see if I can find where the Unions are not being merged but can't see anything. Any thoughts @wyfo ?

**Comment by wyfo** [comment]
I'm sorry for this bug, it has been fixed in #176, and version 0.15.5 including the fix has been deployed right after.

As briefly explained in the PR, GraphQL schema generation use a cache — actually two, the first being a generic one used to handle recursive types in several place in the library — in order to return the same GraphQL type each time the same Python type is visited.
Unions are handled in a particular way, because they have a default type name. 

However, the cache use the name of the type as key (with the description, and the method, to distinguish input and output, because cache must be shared for scalar type, but same type can have both input and output), but the check was done before using default type name generation, so there was no cache entry found or added for unions with default type name.

The PR fix this bug, but as you can read, cache system is IMO too much complex, and I'm not satisfied with the code, so it needs to be reworked. It will surely be done for next version, coming I hope for the end of the month.
