### ISSUE TITLE
id/reference serialization

### ISSUE THREAD

**Issue by thomascobb** [wyfo/apischema#184]
I would like to make a document which contains a list of objects derived from a common base class, some of which contain an id field, and others of which contain a reference to those objects.

For example, if I make an instance of `A` in a document with an `id` propery, then a number of instances of `B`, I would like references by `id` to be turned into object references at deserialize. My attempt is as follows:

```python
from dataclasses import dataclass
from typing import List
from apischema import deserialize, deserializer
from apischema.conversions import Conversion, identity

@dataclass
class Base:
    def __init_subclass__(cls):
        # Deserializers stack directly as a Union
        deserializer(Conversion(identity, source=cls, target=Base))

@dataclass
class A(Base):
    _instances = {}
    id: int

    def __post_init__(self):
        self._instances[self.id] = self

@dataclass
class B(Base):
    a: A

@dataclass
class Container:
    objects: List[Base]

deserializer(Conversion(lambda id: A._instances[id], int, A))

def test_conversion():
    d = {"objects": [{"id": 123}, {"a": 123}]}
    c = deserialize(Container, d)
    a, b = c.objects
    assert a.id == 123
    assert b.a is a
```

However this doesn't seem to work, the `Conversion(int, A)` seems to suppress the standard dict -> dataclass conversion, and I'm not sure how to add it back in. The error I get is:

```python
_______________________________ test_conversion ________________________________
Traceback (most recent call last):
  File "/dls/science/users/tmc43/common/python/ibek/tests/test_conversions.py", line 39, in test_conversion
    c = deserialize(Container, d)
  File "/scratch/tmc43/pipenv/ibek-QWQ4U9sY/lib/python3.7/site-packages/apischema/utils.py", line 546, in wrapper
    return wrapped(*args, **kwargs)
  File "/scratch/tmc43/pipenv/ibek-QWQ4U9sY/lib/python3.7/site-packages/apischema/deserialization/__init__.py", line 878, in deserialize
    )(data)
  File "/scratch/tmc43/pipenv/ibek-QWQ4U9sY/lib/python3.7/site-packages/apischema/deserialization/__init__.py", line 528, in method
    raise ValidationError(errors, field_errors)
apischema.validation.errors.ValidationError: ValidationError(messages=[], children={'objects': ValidationError(messages=(), children={0: ValidationError(messages=['expected type integer, found object'], children={'id': ValidationError(messages=['unexpected property'], children={}), 'a': ValidationError(messages=['missing property'], children={})}), 1: ValidationError(messages=['expected type integer, found object'], children={'a': ValidationError(messages=['123'], children={})})})})
```
Should this be possible?

**Comment by wyfo** [comment]
> However this doesn't seem to work, the Conversion(int, A) seems to suppress the standard dict -> dataclass conversion

Indeed, that's how conversions work. 

> and I'm not sure how to add it back in.

If you want to be able to deserialize `A` from both integer and object/dict, you can register an other conversion, using `apischema.conversions.identity` the following way: 
```python
deserializer(Conversion(identity, source=A, target=A))
a, b = deserialize(list[A], [{"id": 123}, {"a": 123}])
assert a == A(123) and b == B(a) and b.a is a
```
(I realize thanks to your issue that this feature is not really documented; there is only [registered conversion bypass](https://wyfo.github.io/apischema/conversions/#bypass-registered-conversion) but no *identity conversion registration*. I will have to update the documentation, sorry for the inconvenience)

As you know, deserializers stack directly as union, that will give the following JSON schema for `A`:
```python
from apischema.json_schema import deserialization_schema
assert deserialization_schema(A) == {
    "anyOf": [
        {"type": "integer"},
        {
            "type": "object",
            "properties": {"id": {"type": "integer"}},
            "required": ["id"],
            "additionalProperties": False,
        },
    ],
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
}
```
However, as a side effect, it will make `{"a": {"id": 123}}` a valid `B`, which may or may not be intended.

On the other hand, instead of registering a deserializer for `A`, you can also use a [field conversion](https://wyfo.github.io/apischema/conversions/#field-conversions)
```python
from apischema.metadata import conversion
@dataclass
class B:
    a: A = field(metadata=conversion(deserialization=Conversion(lambda id: A._instances[id], int, A))
```
or even use `typing.Annotated`
```python
AFromInt = Annotated[A, conversion(deserialization=Conversion(lambda id: A._instances[id], int, A))]
```
but it depends of course on your use case. With local conversion, `{"a": {"id": 123}}` will not be valid.

**Comment by thomascobb** [comment]
Thanks, I went with the field conversion in the end, that was much cleaner than cluttering the deserialization schema with alternate conversions that only apply in a single place
